/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type Vote = "absent" | "abstain" | "no" | "yes";

export interface AgendaItems {
  id: number;
  time: Timestamp | null;
  title: string | null;
  url: string | null;
}

export interface Ballots {
  agenda_item_id: number | null;
  id: number;
  minutes_url: string | null;
  results_url: string | null;
  time: Timestamp | null;
  title: string | null;
}

export interface Interests {
  category: string | null;
  id: number;
  interest: string | null;
  mp_id: number | null;
}

export interface MembersOfParliament {
  constituency: string | null;
  email: string | null;
  first_name: string | null;
  full_name: string | null;
  id: number;
  minister: boolean | null;
  occupation: string | null;
  party: string | null;
  phone_number: string | null;
  place_of_birth: string | null;
  place_of_residence: string | null;
  year_of_birth: number | null;
}

export interface MpPartyMemberships {
  end_time: Timestamp | null;
  mp_id: number;
  party_id: string;
  start_time: Timestamp;
}

export interface Parties {
  id: string;
  name: string | null;
}

export interface Votes {
  ballot_id: number;
  mp_id: number;
  vote: Vote | null;
}

export interface DB {
  agenda_items: AgendaItems;
  ballots: Ballots;
  interests: Interests;
  members_of_parliament: MembersOfParliament;
  mp_party_memberships: MpPartyMemberships;
  parties: Parties;
  votes: Votes;
}
